import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
import DevIntro from "./_components/DevIntro";
import MiniSidebar from "./_components/MiniSidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "SazzadTanim",
  description:
    "Portfolio Website generated by a professional Bangladeshi developer named SazzadTanim for himself",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-slate-900">
      <body
        className={`font-sans ${inter.variable} mx-auto my-10 grid max-w-[100rem] xl:flex`}
      >
        <TRPCReactProvider cookies={cookies().toString()}>
          <div className="flex w-full">
            <MiniSidebar />
            <DevIntro />
          </div>
          <main className="w-full">{children}</main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
